export const URLS = {
    login: 'api/v1/auth/get-token',
    osgorCreate: 'api/osaga/create',
    osgorView: 'api/osaga/show',
    osgorConfirmPayment: 'api/osaga/confirm-payed',
    osgorCheckPayment: 'api/osaga/check-payment',
    osgorEpolis: 'api/osaga/get-e-polis',
    osgopCreate: 'api/osgop/create',
    osgopView: 'api/osgop/show',
    osgopConfirmPayment: 'api/osgop/confirm-payed',
    osgopCheckPayment: 'api/osgop/check-payment',
    osgopEpolis: 'api/osgop/get-e-polis',
    personalInfoProvider: 'api/provider/personal-info',
    personalInfoNonCitizenProvider: 'api/provider/personal-info-non-citizen',
    organizationInfoProvider: 'api/provider/organization-info',
    vehicleInfoProvider: 'api/provider/vehicle-info',
    vehicleInfoForeignProvider: 'api/provider/vehicle-info-foreign',
    driverLicenceProvider: 'api/provider/driver-licence',
    passengerLicenceProvider: 'api/provider/passenger-licence',
    isPensionerProvider: 'api/provider/is-pensioner',
    isDisabledProvider: 'api/provider/is-disabled',
    regions: 'api/v1/external-clients/regions',
    districts: 'api/v1/external-clients/districts',
    genders: 'api/v1/external-clients/genders',
    residentTypes: 'api/v1/external-clients/resident-types',
    insuranceTerms: 'api/v1/external-clients/terms',
    ownershipForms: 'api/references/ownership-forms',
    agencies: 'api/references/agencies',
    vehicleTypes: 'api/references/vehicle-types',
    okeds: 'api/references/okeds',
    activityAndRisk: 'api/references/activity-and-risks',
    calculator: 'api/osaga/calculate',
    termCategories:'api/v1/external-clients/term-categories',
    accidentTypes:'api/v1/external-clients/accident-types',
    discounts:'api/v1/external-clients/discounts',
}